name: Deploy Backend
on:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
  REGION: us-central1
  IMAGE_PATH: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/flowbit-repo/backend:latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build and Push Container
        run: |
          cd backend
          gcloud builds submit --tag $IMAGE_PATH .

      - name: Deploy API Service
        run: |
          gcloud run deploy flowbit \
            --image $IMAGE_PATH \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --cpu 1 \
            --memory 512Mi \
            --timeout 3600 \
            --set-env-vars "^@^API_ADDR=:8080,APPLY_MIGRATIONS=false,DATABASE_URL=${{ secrets.DATABASE_URL }},ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }},KAFKA_BROKERS=${{ secrets.KAFKA_BROKERS }},KAFKA_TOPIC_JOBS=jobs,KAFKA_CERT_FILE=/secrets/service-cert,KAFKA_KEY_FILE=/secrets/service-key,KAFKA_CA_FILE=/secrets/ca-pem,GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" \
            --set-secrets "/secrets/service-cert=service-cert:latest,/secrets/service-key=service-key:latest,/secrets/ca-pem=ca-pem:latest"

      - name: Deploy Worker Service
        run: |
          gcloud run deploy flowbit-worker \
            --image $IMAGE_PATH \
            --region $REGION \
            --platform managed \
            --no-allow-unauthenticated \
            --cpu 1 \
            --memory 512Mi \
            --timeout 3600 \
            --min-instances=1 \
            --max-instances=1 \
            --cpu-always \
            --concurrency=1 \
            --set-env-vars "^@^API_ADDR=:8080,APPLY_MIGRATIONS=false,DATABASE_URL=${{ secrets.DATABASE_URL }},KAFKA_BROKERS=${{ secrets.KAFKA_BROKERS }},KAFKA_TOPIC_JOBS=jobs,KAFKA_CONSUMER_GROUP=flowbit-workers,KAFKA_CERT_FILE=/secrets/service-cert,KAFKA_KEY_FILE=/secrets/service-key,KAFKA_CA_FILE=/secrets/ca-pem" \
            --set-secrets "/secrets/service-cert=service-cert:latest,/secrets/service-key=service-key:latest,/secrets/ca-pem=ca-pem:latest" \
            --command "/worker"
