name: Deploy Flowbit Fullstack
on:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # 3. BACKEND: Build to the repo, deploy to the 'flowbit' service
      - name: Deploy Backend
        run: |
          cd backend

          # Correct Registry Name
          IMAGE_PATH="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/flowbit-repo/backend:latest"

          # 1. Build and push the container manually
          gcloud builds submit --tag $IMAGE_PATH .

          # 2. Force the 'flowbit' service to use this new container image
          gcloud run deploy flowbit \
            --image $IMAGE_PATH \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
