name: Deploy Frontend
on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}'

      - name: Install and Build
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          # This line is mandatory for the action to start, 
          # even when using Workload Identity.
          firebaseServiceAccount: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          projectId: ${{ secrets.GCP_PROJECT_ID }}
          channelId: live
          entryPoint: ./frontend
